name: Build and Deploy

on:
  push:
    branches: [main , dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build